name: Tests

on: [push]

jobs: 
  jennifer:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v6
      - name: install dependecies
        run: npm install
      - name: run Tests
        run: npm test
  